import type { Metadata } from "next";
import { Geist, Geist_Mono, PT_Mono, Palette_Mosaic } from "next/font/google";
import Link from "next/link";
import "./globals.css";


const paletteMosaic = Palette_Mosaic({
  subsets: ["latin"],
  weight:'400'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar(){
  return(
    <div className="flex flex-row items-center justify-between bg-zinc-50 px-4 py-2 dark:bg-black">
      <Link 
      href={"/button_demo"}
      >
        Buttom Demo
      </Link>

      <Link
      href={'/card_demo'}
      >
        Card Demo
      </Link>
    </div>
  )}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${paletteMosaic.className} h-full antialiased`}>
      <Navbar />
      <body className="min-h-full flex flex-col">
        
        {children}
      </body>
    </html>
  );
}
